# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname funnel
#' @export
cpp_funnel <- function(a, b) {
    .Call(`_funnel_cpp_funnel`, a, b)
}

#' @rdname funnel2
#' @export
cpp_funnel2 <- function(x, wordset) {
    .Call(`_funnel_cpp_funnel2`, x, wordset)
}

#' Part 2 Bonus 2
#'
#' Find the depth of a word funnel when more than one letter can be skipped in
#' a single step.
#'
#' @param x The word to test.
#' @param wordset The list of valid wods as an external pointer to a C++
#'   unordered set.
#' @export
pt2_bonus2 <- function(x, wordset, depth = 1L) {
    .Call(`_funnel_pt2_bonus2`, x, wordset, depth)
}

#' Create an external pointer to a C++ unordered set
#'
#' @param s The character vector to be used in the set.
#' @export
initialize_set <- function(s) {
    .Call(`_funnel_initialize_set`, s)
}

set_contains <- function(word, table) {
    .Call(`_funnel_set_contains`, word, table)
}

