# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname funnel
#' @export
cpp_funnel <- function(a, b) {
    .Call(`_funnel_cpp_funnel`, a, b)
}

initialize_set <- function(s) {
    .Call(`_funnel_initialize_set`, s)
}

set_contains <- function(word, table) {
    .Call(`_funnel_set_contains`, word, table)
}

