CC = gcc
CCFLAGS = -O2

.PHONY: all

all: necklace repeats bonus2

necklace: necklace.c
	$(CC) $^ -o $@

repeats: repeats.c
	$(CC) $^ -o $@

bonus2: bonus2.c
	$(CC) $^ -o $@

clean:
	rm necklace repeats bonus2
